baseurl = "https://matthewsmith.rbind.io/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Network Science"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "UA-150532545-1"
enableEmoji= true
relativeURLs = true

[Params]
  subtitle = "Matthew Smith"
  logo = "img/NetworkScience2a.png"
  favicon = "img/academic.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true
  socialShare = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Matthew Smith"
  email = "M.Smith3@napier.ac.uk"
  github = "MatthewSmith430"
  twitter = "@SmithMatt90"
  linkedin = "matthew-smith-71493742"
  orcid = "https://orcid.org/0000-0002-3430-2176"
  google-scholar = "https://scholar.google.com/citations?user=sM6feS4AAAAJ&hl=en"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1


[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "R Packages"
    url = "page/r-packages/"
    weight = 3
    
[[menu.main]]
    name = "Projects and Publications"
    url = "page/projects/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
