[build]
  #publish = "exampleSite/public"
  publish = "public"
  #command = "cd exampleSite && hugo --gc --themesDir ../.."
  #command = "./build.sh"
  command = "hugo"
  
[build.environment]
  HUGO_VERSION = "0.116.1"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[context.production.environment]
  HUGO_ENV = "production"